
export const actionType = {
    SET_PRODUCTS : "SET_PRODUCTS",
    RATING_PRODUCTS : "RATING_PRODUCTS",
    SELECTED_PRODUCT : "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT : "REMOVE_SELECTED_PRODUCT",
    SET_USERS : "SET_USERS"

};

